on:
  pull_request:
  push:
    branches:
      - main

name: Build

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Setup Cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Run Cargo:fmt
        run: cargo fmt --all -- --check
        continue-on-error: false

      - name: Run Cargo:clippy
        run: cargo clippy --all-features -- -D warnings
        continue-on-error: false

      - name: Run Cargo:test
        run: cargo test --all-features
        continue-on-error: false
